smtp_address: 'smtp.testdomain.com'
smtp_port: '25'
smtp_domain: 'testdomain.com'
smtp_user_name: ''
smtp_password: ''
smtp_from: ''
fb_id: ''
fb_secret: ''
vk_id: ''
vk_secret: ''
ok_id: ''
ok_secret: ''
ok_public: ''
instagram_id: ''
instagram_secret: ''
production:
  smtp_host: 'testdomain.com'
  protocol: 'https'
  domain: 'testdomain.com'
  url: 'https://testdomain.com'
development:
  smtp_host: 'localhost'
  protocol: 'http'
  domain: 'localhost'
  url: 'http://localhost:3000'
  #smtp_check: 'yes'
